// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnbEMHjM7X5cffhxCI6O-5Ybl-oNe6W8',
    appId: '1:842021422503:web:74357e5959cee7648fa282',
    messagingSenderId: '842021422503',
    projectId: 'tensai-ai-app',
    authDomain: 'tensai-ai-app.firebaseapp.com',
    storageBucket: 'tensai-ai-app.firebasestorage.app',
    measurementId: 'G-8W4S20DLPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm_ptVxk1O5AGaGaICsiXoUSvz4EHmag',
    appId: '1:842021422503:android:e2615b4e6f399e518fa282',
    messagingSenderId: '842021422503',
    projectId: 'tensai-ai-app',
    storageBucket: 'tensai-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sVGf0-qG3e9LzTkZZETcF6NZYOwkpIg',
    appId: '1:842021422503:ios:7ea81bf4281f9ee28fa282',
    messagingSenderId: '842021422503',
    projectId: 'tensai-ai-app',
    storageBucket: 'tensai-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.tensai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7sVGf0-qG3e9LzTkZZETcF6NZYOwkpIg',
    appId: '1:842021422503:ios:7ea81bf4281f9ee28fa282',
    messagingSenderId: '842021422503',
    projectId: 'tensai-ai-app',
    storageBucket: 'tensai-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.tensai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDnbEMHjM7X5cffhxCI6O-5Ybl-oNe6W8',
    appId: '1:842021422503:web:c4cbdfc4e47718a58fa282',
    messagingSenderId: '842021422503',
    projectId: 'tensai-ai-app',
    authDomain: 'tensai-ai-app.firebaseapp.com',
    storageBucket: 'tensai-ai-app.firebasestorage.app',
    measurementId: 'G-0Q531WZWQD',
  );
}
